<a href="https://colab.research.google.com/github/RamaBharti/Machine-Learning-Models-for-Connect-4-Game-Prediction/blob/master/q1_ANN.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!wget https://archive.ics.uci.edu/ml/machine-learning-databases/connect-4/connect-4.data.Z
!uncompress connect-4.data.Z


import urllib.request
import gzip
import numpy as np
import pandas as pd
from sklearn.neural_network import MLPClassifier
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import GridSearchCV
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import MinMaxScaler
from scipy.stats import randint
from sklearn.metrics import accuracy_score
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix
from sklearn.model_selection import train_test_split, RandomizedSearchCV

# Define mapping for 'b', 'o', and 'x'
mapping = {'b': 0, 'o': 1, 'x': 2}

# Read dataset and replace values with integers
df = pd.read_csv('connect-4.data', header=None)
df.replace(mapping, inplace=True)

# Define mapping for 'won', 'loss', and 'draw'
outcome_mapping = {'win': 1, 'loss': 0, 'draw': 2}

# Replace outcome values with integers
df.replace(outcome_mapping, inplace=True)



#df = pd.read_csv('connect-4.data', header=None)



# Separate the target variable from the rest of the data
X = df.iloc[:, :-1]
y = df.iloc[:, -1]
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)



# Create an ANN classifier
ann_clf = MLPClassifier()
ann_clf.fit(X_train, y_train)
y_pred = ann_clf.predict(X_test)
accuracy = accuracy_score(y_test, y_pred)
print('Accuracy_ann_clf: ', accuracy)
print("Precision:", precision_score(y_test, y_pred, average='macro'))
print("Recall:", recall_score(y_test, y_pred, average='macro'))
print("F1-score:", f1_score(y_test, y_pred, average='macro'))
print("Confusion matrix:\n", confusion_matrix(y_test, y_pred))

scores = cross_val_score(ann_clf, X_train, y_train, cv=5, n_jobs=-1)
# Print the cross-validation scores
print('Cross-Validation Scores: ', scores)

# Define the hyperparameters for grid search
param_grid = {
    'hidden_layer_sizes': [(100,), (100, 50), (50,)],
    'activation': ['relu', 'tanh', 'logistic'],
    'solver': ['adam', 'sgd'],
    'alpha': [0.0001, 0.001, 0.01]
}

# Perform grid search with cross-validation
grid_search = GridSearchCV(ann_clf, param_grid, cv=3, n_jobs=-1)
grid_search.fit(X_train, y_train)

# Print the best hyperparameters and score
print('Best Hyperparameters: ', grid_search.best_params_)
print('Best Score: ', grid_search.best_score_)
best_model = grid_search.best_estimator_
y_pred = best_model.predict(X_test)

# Calculate the evaluation metrics
accuracy = accuracy_score(y_test, y_pred)
print('Accuracy_grid: ', accuracy)
print("Precision:", precision_score(y_test, y_pred, average='macro'))
print("Recall:", recall_score(y_test, y_pred, average='macro'))
print("F1-score:", f1_score(y_test, y_pred, average='macro'))
print("Confusion matrix:\n", confusion_matrix(y_test, y_pred))


# Create an ANN classifier with best hyperparameters
ann_clf = MLPClassifier(hidden_layer_sizes=(100, 50), activation='relu', solver='adam', alpha=0.0001)

# Evaluate the ANN classifier using k-fold cross-validation
scores = cross_val_score(ann_clf, X_train, y_train, cv=5, n_jobs=-1)
# Print the cross-validation scores
print('Cross-Validation Scores: ', scores)
ann_clf.fit(X_train,y_train)
# Make predictions on the test set
y_pred = ann_clf.predict(X_test)

# Calculate the evaluation metrics
accuracy = accuracy_score(y_test, y_pred)
print('Accuracy of best: ', accuracy)
print("Precision:", precision_score(y_test, y_pred, average='macro'))
print("Recall:", recall_score(y_test, y_pred, average='macro'))
print("F1-score:", f1_score(y_test, y_pred, average='macro'))
print("Confusion matrix:\n", confusion_matrix(y_test, y_pred))

--2023-03-29 02:38:17--  https://archive.ics.uci.edu/ml/machine-learning-databases/connect-4/connect-4.data.Z
Resolving archive.ics.uci.edu (archive.ics.uci.edu)... 128.195.10.252
Connecting to archive.ics.uci.edu (archive.ics.uci.edu)|128.195.10.252|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 403464 (394K) [application/x-httpd-php]
Saving to: ‘connect-4.data.Z’

connect-4.data.Z    100%[===================>] 394.01K  1.20MB/s    in 0.3s    

2023-03-29 02:38:18 (1.20 MB/s) - ‘connect-4.data.Z’ saved [403464/403464]

gzip: connect-4.data already exists; do you wish to overwrite (y or n)? y
Accuracy_ann_clf:  0.8095026642984015
Precision: 0.6646651007828054
Recall: 0.6087036653571164
F1-score: 0.6154764731680594
Confusion matrix:
 [[2510  673  158]
 [ 522 8238  116]
 [ 429  676  190]]


/usr/local/lib/python3.9/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(


Cross-Validation Scores:  [0.81071329 0.81052826 0.81043575 0.80803035 0.80682764]


/usr/local/lib/python3.9/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(


Best Hyperparameters:  {'activation': 'tanh', 'alpha': 0.01, 'hidden_layer_sizes': (100,), 'solver': 'adam'}
Best Score:  0.8194097511333148
Accuracy_grid:  0.8177175843694494
Precision: 0.6785424860389219
Recall: 0.6290690492534138
F1-score: 0.6246125081276042
Confusion matrix:
 [[2788  464   89]
 [ 666 8076  134]
 [ 571  539  185]]
Cross-Validation Scores:  [0.8143214  0.805995   0.79239523 0.8035896  0.80756777]
Accuracy of best:  0.8163854351687388
Precision: 0.6768466994212531
Recall: 0.6394487510218647
F1-score: 0.650521638981525
Confusion matrix:
 [[2524  596  221]
 [ 452 8197  227]
 [ 401  584  310]]


/usr/local/lib/python3.9/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
