<a href="https://colab.research.google.com/github/RamaBharti/Machine-Learning-Models-for-Connect-4-Game-Prediction/blob/master/q1_naive_bayes.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!wget https://archive.ics.uci.edu/ml/machine-learning-databases/connect-4/connect-4.data.Z
!uncompress connect-4.data.Z

import pandas as pd
from sklearn.model_selection import GridSearchCV, cross_val_score
from scipy.stats import randint
from sklearn.model_selection import RandomizedSearchCV
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix
import numpy as np
from sklearn.naive_bayes import MultinomialNB
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import MinMaxScaler





# Define mapping for 'b', 'o', and 'x'
mapping = {'b': 0, 'o': 1, 'x': 2}

# Read dataset and replace values with integers
df = pd.read_csv('connect-4.data', header=None)
df.replace(mapping, inplace=True)

# Define mapping for 'won', 'loss', and 'draw'
outcome_mapping = {'win': 1, 'loss': 0, 'draw': 2}

# Replace outcome values with integers
df.replace(outcome_mapping, inplace=True)



#df = pd.read_csv('connect-4.data', header=None)



# Separate the target variable from the rest of the data
X = df.iloc[:, :-1]
y = df.iloc[:, -1]
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)


scaler = MinMaxScaler()
X_train_scaled = scaler.fit_transform(X_train)

nb = MultinomialNB()
nb.fit(X_train, y_train)
y_pred =nb.predict(X_test)
print('Accuracy_nb:', accuracy_score(y_test, y_pred))
print("Precision:", precision_score(y_test, y_pred, average='macro'))
print("Recall:", recall_score(y_test, y_pred, average='macro'))
print("F1-score:", f1_score(y_test, y_pred, average='macro'))
print("Confusion matrix:\n", confusion_matrix(y_test, y_pred))

pipe = Pipeline([('scaler', MinMaxScaler()), ('nb', nb)])
params = {'nb__alpha': [0.95, 0.97, 0.99, 0.1, 0.2, 0.3, 0.4, 0.5, 1.0, 1.5, 2.0]}
grid = GridSearchCV(pipe, param_grid=params, cv=5)
grid.fit(X_train, y_train)
print('Best Parameters:', grid.best_params_)
print('Best Score:', grid.best_score_)
#best_params=grid.best_score_
y_pred = grid.predict(X_test)
print('Accuracy_grid:', accuracy_score(y_test, y_pred))
print("Precision:", precision_score(y_test, y_pred, average='macro'))
print("Recall:", recall_score(y_test, y_pred, average='macro'))
print("F1-score:", f1_score(y_test, y_pred, average='macro'))
print("Confusion matrix:\n", confusion_matrix(y_test, y_pred))

nbc=grid.best_estimator_
y_pred =nbc.predict(X_test)
print('Accuracy_nbc:', accuracy_score(y_test, y_pred))
print("Precision:", precision_score(y_test, y_pred, average='macro'))
print("Recall:", recall_score(y_test, y_pred, average='macro'))
print("F1-score:", f1_score(y_test, y_pred, average='macro'))
print("Confusion matrix:\n", confusion_matrix(y_test, y_pred))

--2023-03-28 17:39:21--  https://archive.ics.uci.edu/ml/machine-learning-databases/connect-4/connect-4.data.Z
Resolving archive.ics.uci.edu (archive.ics.uci.edu)... 128.195.10.252
Connecting to archive.ics.uci.edu (archive.ics.uci.edu)|128.195.10.252|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 403464 (394K) [application/x-httpd-php]
Saving to: ‘connect-4.data.Z’

connect-4.data.Z    100%[===================>] 394.01K  1.91MB/s    in 0.2s    

2023-03-28 17:39:21 (1.91 MB/s) - ‘connect-4.data.Z’ saved [403464/403464]

Accuracy_nb: 0.6306986382474837
Precision: 0.40045654002385284
Recall: 0.3536376176091896
F1-score: 0.3191488682682917
Confusion matrix:
 [[ 116 3010  215]
 [ 156 8286  434]
 [  34 1141  120]]
Best Parameters: {'nb__alpha': 0.1}
Best Score: 0.6583217688962902
Accuracy_grid: 0.6567495559502664
Precision: 0.32159267258163476
Recall: 0.33413760763918493
F1-score: 0.26632178998741457
Confusion matrix:
 [[   0 3338    3]
 [   0 8870    6]
 [   0 12

/usr/local/lib/python3.9/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.9/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
