<a href="https://colab.research.google.com/github/RamaBharti/Machine-Learning-Models-for-Connect-4-Game-Prediction/blob/master/q1_svm.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!wget https://archive.ics.uci.edu/ml/machine-learning-databases/connect-4/connect-4.data.Z
!uncompress connect-4.data.Z


import urllib.request
import pandas as pd
import gzip
import numpy as np
from sklearn.model_selection import train_test_split, GridSearchCV, RandomizedSearchCV
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix
from sklearn.svm import SVC
from sklearn.model_selection import cross_val_score
from sklearn.preprocessing import MinMaxScaler
#from sklearn.datasets import fetch_openml


# Define mapping for 'b', 'o', and 'x'
mapping = {'b': 0, 'o': 1, 'x': 2}

# Read dataset and replace values with integers
df = pd.read_csv('connect-4.data', header=None)
df.replace(mapping, inplace=True)

# Define mapping for 'won', 'loss', and 'draw'
outcome_mapping = {'win': 1, 'loss': 0, 'draw': 2}

# Replace outcome values with integers
df.replace(outcome_mapping, inplace=True)


#df = pd.read_csv('connect-4.data', header=None)


# Separate the target variable from the rest of the data
X = df.iloc[:, :-1]
y = df.iloc[:, -1]
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)


scaler = MinMaxScaler()
X_train_scaled = scaler.fit_transform(X_train)

svm_model = SVC()
svm_model.fit(X_train,y_train)
y_pred = svm_model.predict(X_test)
print('Accuracy:', accuracy_score(y_test, y_pred))
print("Precision:", precision_score(y_test, y_pred, average='macro'))
print("Recall:", recall_score(y_test, y_pred, average='macro'))
print("F1-score:", f1_score(y_test, y_pred, average='macro'))
print("Confusion matrix:\n", confusion_matrix(y_test, y_pred))


scores = cross_val_score(svm_model, X_train, y_train, cv=5)
print(f"Accuracy_cross: {scores.mean():.2f} +/- {scores.std():.2f}")


"""
param_grid = {'C': [0.1, 1, 10],
              'kernel': ['linear', 'rbf', 'sigmoid'],
              'gamma': [0.01, 0.1, 1]}
svm_grid = GridSearchCV(svm_model, param_grid, cv=5, n_jobs=-1)
svm_grid.fit(X_train, y_train)
print('Best parameters:', svm_grid.best_params_)
y_pred = svm_grid.predict(X_test)
print('Accuracy_grid:', accuracy_score(y_test, y_pred))
svmg=svm_grid.best_estimator_
y_pred =svmg.predict(X_test)
print('Accuracy_grid_best:', accuracy_score(y_test, y_pred))
"""
param_dist = {'C': [0.1, 1, 10],
              'kernel': ['linear', 'rbf'],
              'gamma': [0.01, 0.1, 1]}
svm_random = RandomizedSearchCV(svm_model, param_dist, cv=5, n_jobs=-1)
svm_random.fit(X_train, y_train)
print('Best parameters:', svm_random.best_params_)
y_pred = svm_random.predict(X_test)
print('Accuracy_random:', accuracy_score(y_test, y_pred))
svmr=svm_random.best_estimator_
y_pred =svmr.predict(X_test)
print('Accuracy_random_best:', accuracy_score(y_test, y_pred))
print("Precision:", precision_score(y_test, y_pred, average='macro'))
print("Recall:", recall_score(y_test, y_pred, average='macro'))
print("F1-score:", f1_score(y_test, y_pred, average='macro'))
print("Confusion matrix:\n", confusion_matrix(y_test, y_pred))

--2023-03-28 18:28:52--  https://archive.ics.uci.edu/ml/machine-learning-databases/connect-4/connect-4.data.Z
Resolving archive.ics.uci.edu (archive.ics.uci.edu)... 128.195.10.252
Connecting to archive.ics.uci.edu (archive.ics.uci.edu)|128.195.10.252|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 403464 (394K) [application/x-httpd-php]
Saving to: ‘connect-4.data.Z’

connect-4.data.Z    100%[===================>] 394.01K   609KB/s    in 0.6s    

2023-03-28 18:28:53 (609 KB/s) - ‘connect-4.data.Z’ saved [403464/403464]

Accuracy: 0.7743487270574304
Precision: 0.5088255462683898
Recall: 0.5140669475078883
F1-score: 0.5051012050386011
Confusion matrix:
 [[1947 1394    0]
 [ 360 8516    0]
 [ 306  989    0]]


/usr/local/lib/python3.9/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


Accuracy_cross: 0.77 +/- 0.00
Best parameters: {'kernel': 'rbf', 'gamma': 1, 'C': 10}
Accuracy_random: 0.7966992303137952
Accuracy_random_best: 0.7966992303137952
Precision: 0.7162806644419527
Recall: 0.5568876631188676
F1-score: 0.5790845723584098
Confusion matrix:
 [[1983 1287   71]
 [ 182 8649   45]
 [ 264  898  133]]
